== Klassenbeschreibung
=== Topic `+Stammdaten+`
Das Topic `+Stammdaten+` umfasst alle statischen Werte. Darunter fallen z.B. die Aufzählwerte von Listen (INTERLIS-Datentyp «Aufzählung»). Jede Liste wird in einer eigenen Klasse modelliert.

Die Stammdaten werden durch die zuständige Stelle vorgegeben. Bei Bundesthemen ist dies das für die Modellierung zuständige Bundesamt. Bei kantonalen Themen das zuständige kantonale Amt. Die Stammdaten von Bundesthemen können auf der Stufe Kanton erweitert werden. Die kantonalen Erweiterungen werden bei der Überführung ins Bundesmodell den entsprechenden Bundestypen zugeordnet. Bei Bedarf werden die Stammdaten durch die Abteilung Geoinformation nachgeführt und im https://github.com/ch-sz-geo/A000_template/tree/main/data[data-Verzeichnis] des jeweiligen Themas veröffentlicht.

==== Klasse `+Katalogeintrag+`
Die Klasse `+Katalogeintrag+` enthält die allgemeinen, für alle Kataloge gemeinsamen Attribute. Die Klasse selber ist abstrakt: Es gibt keine Objekte `+Katalogeintrag+`, sondern nur Objekte von den spezialisierten Klassen.

[cols="10%, 60%, 20%, 10%",options="header"]
|===
| Name | Beschreibung | Beispiel | Freigabe
m| OID
| technischer Objektidentifikator
| ceaa37a9-8614-43fc-9a8b-688f95c30218
| öffentlich
m| Code
| Code des Listeneintrages; entspricht in INTERLIS dem Wert der Aufzählung und muss ein gültiger INTERLIS-Name sein (siehe https://www.interlis.ch/dokumentation[INTERLIS-Referenzhandbuch])
| in_Aenderung
| öffentlich
m| Name
| Bezeichnung des Katalogeintrages, wie er den Nutzenden angezeigt wird
| in Änderung
| öffentlich
m| SortierNr
| Reihenfolge des Katalogeintrages in der Auswahlliste
| 1
| öffentlich
m| Bemerkung
| Erläuterung, welche den Katalogeintrag näher beschreibt
| Dieser Status wird für alle Objekte verwendet, bei denen aktuell eine Nachführung läuft.
| öffentlich
|===

==== Klasse `+Nutzungszustand+`
Die Klasse `+Nutzungszustand+` führt die Werte des Katalogs "Nutzungszustand". Sie ist eine Spezialisierung der Klasse `+Katalogeintrag+` und führt keine weiteren Attribute.

[cols=4*,options="header"]
|===
| Name | Beschreibung | Beispiel | Freigabe
4+| _Diese Klasse führt keine zusätzlichen Attribute_
4+| *Anforderungen*
m|Code
3+| Die Werte müssen eindeutig sein
m|Name
3+| Die Werte müssen eindeutig sein
|===

==== Klasse `+Grundwasserleitertyp+`
Die Klasse `+Grundwasserleitertyp+` führt die Werte des Katalogs "Grundwasserleitertyp". Sie ist eine Spezialisierung der Klasse `+Katalogeintrag+` und führt keine weiteren Attribute.

[cols=4*,options="header"]
|===
| Name | Beschreibung | Beispiel | Freigabe
4+| _Diese Klasse führt keine zusätzlichen Attribute_
4+| *Anforderungen*
m|Code
3+| Die Werte müssen eindeutig sein
m|Name
3+| Die Werte müssen eindeutig sein
|===

==== Klasse `+Fassungsart+`
Die Klasse `+Fassungsart+` führt die Werte des Katalogs "Fassungsart". Sie ist eine Spezialisierung der Klasse `+Katalogeintrag+` und führt keine weiteren Attribute.

[cols=4*,options="header"]
|===
| Name | Beschreibung | Beispiel | Freigabe
4+| _Diese Klasse führt keine zusätzlichen Attribute_
4+| *Anforderungen*
m|Code
3+| Die Werte müssen eindeutig sein
m|Name
3+| Die Werte müssen eindeutig sein
|===

==== Klasse `+Wasserversorger+`
Die Klasse `+Wasserversorger+` führt die Werte des Katalogs "Wasserversorger". Sie ist eine Spezialisierung der Klasse `+Katalogeintrag+` und führt keine weiteren Attribute.

[cols=4*,options="header"]
|===
| Name | Beschreibung | Beispiel | Freigabe
4+| _Diese Klasse führt keine zusätzlichen Attribute_
4+| *Anforderungen*
m|Code
3+| Die Werte müssen eindeutig sein
m|Name
3+| Die Werte müssen eindeutig sein
|===

==== Klasse `+Brunnenart+`
Die Klasse `+Brunnenart+` führt die Werte des Katalogs "Brunnenart". Sie ist eine Spezialisierung der Klasse `+Katalogeintrag+` und führt keine weiteren Attribute.

[cols=4*,options="header"]
|===
| Name | Beschreibung | Beispiel | Freigabe
4+| _Diese Klasse führt keine zusätzlichen Attribute_
4+| *Anforderungen*
m|Code
3+| Die Werte müssen eindeutig sein
m|Name
3+| Die Werte müssen eindeutig sein
|===

==== Klasse `+Foerdermethode+`
Die Klasse `+Foerdermethode+` führt die Werte des Katalogs "Foerdermethode". Sie ist eine Spezialisierung der Klasse `+Katalogeintrag+` und führt keine weiteren Attribute.

[cols=4*,options="header"]
|===
| Name | Beschreibung | Beispiel | Freigabe
4+| _Diese Klasse führt keine zusätzlichen Attribute_
4+| *Anforderungen*
m|Code
3+| Die Werte müssen eindeutig sein
m|Name
3+| Die Werte müssen eindeutig sein
|===

==== Klasse `+Anreicherungstyp+`
Die Klasse `+Anreicherungstyp+` führt die Werte des Katalogs "Anreicherungstyp". Sie ist eine Spezialisierung der Klasse `+Katalogeintrag+` und führt keine weiteren Attribute.

[cols=4*,options="header"]
|===
| Name | Beschreibung | Beispiel | Freigabe
4+| _Diese Klasse führt keine zusätzlichen Attribute_
4+| *Anforderungen*
m|Code
3+| Die Werte müssen eindeutig sein
m|Name
3+| Die Werte müssen eindeutig sein
|===

==== Klasse `+Fassungstyp+`
Die Klasse `+Fassungstyp+` führt die Werte des Katalogs "Fassungstyp". Sie ist eine Spezialisierung der Klasse `+Katalogeintrag+` und führt keine weiteren Attribute.

[cols=4*,options="header"]
|===
| Name | Beschreibung | Beispiel | Freigabe
4+| _Diese Klasse führt keine zusätzlichen Attribute_
4+| *Anforderungen*
m|Code
3+| Die Werte müssen eindeutig sein
m|Name
3+| Die Werte müssen eindeutig sein
|===

=== Topic `+Fachdaten+`
Das Topic `+Fachdaten+` umfasst die eigentlichen, fachlichen Klassen des Themas.

==== Klasse `+Klasse1+`
Die Klasse `+Klasse1+` führt .....

[cols=4*,options="header"]
|===
| Name | Beschreibung | Beispiel | Freigabe
4+| *Fachattribute*
m| OID
| technischer Objektidentifikator
| ceaa37a9-8614-43fc-9a8b-688f95c30218
| öffentlich
m| erfasstVon
| Loginname der Person, welche den Datensatz erstellt hat (Autor); wird durch das System gesetzt
| Musterha
| intern
m| erfasstAm
| Datum und Zeit, an dem der Datensatz erstellt wurde; wird durch das System gesetzt
| 1980-03-21T15:38:12
| intern
m| geaendertVon
| Loginname der Person, welche den Datensatz zuletzt geändert hat (Editor); wird durch das System gesetzt
| Muelleran
| intern
m| geaendertAm
| Datum und Zeit, an dem der Datensatz zuletzt geändert wurde; wird durch das System gesetzt
| 2024-07-30T08:07:57
| intern
m| Kennung
| fortlaufende, einfach aufgebaute Kennung, welche sich zur Identifikation eignet
| GA1159
| öffentlich
m| KennungAlt
| Nummer aus dem alten geologischen Archiv; entspricht "IDAlternate" aus DM_GeolAssets_V2
| GA01.2.1461
| öffentlich
m| Titel
| Titel des Dokuments; entspricht "IDAlternate" aus DM_GeolAssets_V2
| UVP:GeolGeotecGutachtenzumVorprojekt
| öffentlich
m| Erstelldatum
| Datum des Berichtes; entspricht "DateCreation" aus DM_GeolAssets_V2
| 1985-03-21
| öffentlich
m| Dokumentlink
| Link, über den auf das Dokument zugegrifen werden kann; Pfad zum Speicher- bzw. Ablageort des Dokuments
| Q:\...\2021-01-18-0303_NB_Standseilbahn_Stoos_Bauproj_KL.pdf
| öffentlich
m| Baugesuchsnummer
| Kennung des Baugesuches, welches mit dem Dokument in Verbindung steht
| B2019-0421
| öffentlich
m| Autor
| Kennung der Objekt-ID des Unternehmens, welches den Bericht verfasst hat. Auf eine ausmodellierte Beziehung wird der Einfachheit halber verzichtet, so dass hier nur die ID eingetragen werden muss.
| 2a150ef7-eb3d-4661-99d6-52d6eb7a5fd0
| öffentlich
m| Bemerkung
| Kommentar zum entsprechenden Dokument; entspricht "Description" aus DM_GeolAssets_V2
| Das ist meine Bemerkung zu diesem Dokument.
| öffentlich
4+| *Beziehungsattribute*
m| rGeometrie
| Fremdschlüssel zur Geometrie, welche mit dem Dokument verknüpft ist.
| ccee2bad-419e-454e-9e0f-9ef2ae2d4d44
| öffentlich
m| rInhalt
| Fremdschlüssel zum Inhalt (Stammdaten); entspricht "Kind" aus DM_GeolAssets_V2
| e0807260-956b-40a2-871a-e32c51ebf192 (für "Bohrprofil")
| öffentlich
4+| *Geometrie*
m| Geometrie
| Geometrie des Objektes
| (ohne Beispiel)
| öffentlich
4+| *Bedingungen*
m|Kennung
3+a| * Die Werte müssen innerhalb der Klasse eindeutig sein.
* Nach der Vergabe muss der Wert unverändert bleiben.
|===

ifdef::backend-pdf[]
<<<
endif::[]
