== Modelltransformationen
=== Transformation ins minimale Geodatenmodell des Bundes
Die Daten für das Bundesthema "Grundwasseraustritte" liegen beim Kanton in zwei verschiedenen Themen: "Inventar Trinkwasserversorgung in Mangellagen (A059)" und der "Wärmenutzung (A034)". Aus diesem Grund wird kein eigenens Datenmodell erstellt. Bei der Abtabe gemäss Bundesmodell werden die Daten entsprechend der unten aufgeführten Abbildung überführt.

* Quellmodelle:
** Das Datenmodell des Themas https://ch-sz-geo.github.io/A034/docs/modelldokumentation.html[A034]
** Das Datenmodell des Themas https://ch-sz-geo.github.io/A059/docs/modelldokumentation.html[A059]
* Zielmodell: https://models.geo.admin.ch/BAFU/Grundwasseraustritte_V2_0.ili[Grundwasseraustritte_V2_0 (Version: 2024-09-11)]

==== Klasse `+Quelle+`
[cols=2*,options="header"]
|===
| Quellattribut | Zielattribut
| zusammengesetzter Wert; +
Muster: "SZ"-`+Quelle.OID+` +
Beispiel: SZ-123e4567-e89b-12d3-a456-426614174000
| `+Identifikator+`
| `+Name+`
| `+Name+`
| `+Grundwasserleitertyp.Code+` +
hergeleitet über `+Quelle.rGrundwasserleitertyp+`
| `+Grundwasserleiter_Typ+`
| `+Quelltyp+`
| `+Quelltyp+`
| `+Fassungsart.Code+` +
hergeleitet über `+Quelle.rFassungsart+`
| `+Fassungsart+`
| `+Nutzungszustand.Code+` +
hergeleitet über `+Quelle.rNutzungszustand+`
| `+Nutzungszustand+`
| `+ist_Trinkwasser+` +
Regel: "1" = "ja"; "0" = "nein"; leer = "unbekannt"
| `+Trinkwasser+`
| `+Zweck+`
| `+Zweck+`
| `+ist_Interesse_oeffentlich+`
| `+Oeffentliches_Interesse+`
| `+Schuettung_minimal+`
| `+Schuettung_minimal+`
| `+Schuettung_mittel+`
| `+Schuettung_mittel+`
| `+Schuettung_maximal+`
| `+Schuettung_maximal+`
| `+ist_Zustroembereich_erforderlich+`
| `+Zustroembereich_erforderlich+`
| `+Geometrie+`
| `+Geometrie+`
| `+Wasserversorger+`
| `+Name_WV+`
| berechneter Wert; +
OID aus Grundwasserschutzzone aufgrund geometrischem Verschnitt
| `+Ref_GWSZone+`
| berechneter Wert; +
OID aus Grundwasserschutzbereich aufgrund geometrischem Verschnitt
| `+Ref_GSBereich+`
|===

todo: Erfassungsregeln gemäss Bundesmodell bei der Klassenbeschreibung ergänzen

==== Klasse `+Grundwasserbrunnen+`
[cols=2*,options="header"]
|===
| Quellattribut | Zielattribut
| zusammengesetzter Wert; +
Muster: "SZ"-`+Quelle.OID+` +
Beispiel: SZ-123e4567-e89b-12d3-a456-426614174000
| `+Identifikator+`
| `+Name+`
| `+Name+`
| `+Brunnenart.Code+` +
hergeleitet über `+Grundwasserbrunnen.rBrunnenart+`
| Brunnenart
| `+Foerdermethode.Code+` +
hergeleitet über `+Grundwasserbrunnen.rFoerdermethode+`
| Foerdermethode
| `+Nutzungszustand.Code+` +
hergeleitet über `+Grundwasserbrunnen.rNutzungszustand+`
| `+Nutzungszustand+`
| `+ist_Trinkwasser+` +
Regel: "1" = "ja"; "0" = "nein"; leer = "unbekannt"
| `+Trinkwasser+`
| `+Zweck+`
| `+Zweck+`
| `+ist_Interesse_oeffentlich+`
| `+Oeffentliches_Interesse+`
| `+Entnahmemenge+`
| `+Pkonz+`
| `+Entnahmemenge_Gruppe+`
| `+Pkonz_gruppe+`
| `+ist_Zustroembereich_erforderlich+`
| `+Zustroembereich_erforderlich+`
| `+Geometrie+`
| `+Geometrie+`
| `+Wasserversorger+`
| `+Name_WV+`
| berechneter Wert; +
OID aus Grundwasserschutzzone aufgrund geometrischem Verschnitt
| `+Ref_GWSZone+`
| berechneter Wert; +
OID aus Grundwasserschutzbereich aufgrund geometrischem Verschnitt
| `+Ref_GSBereich+`
|===

==== Klasse `+Rueckgabebrunnen+`
[cols=2*,options="header"]
|===
| Quellattribut | Zielattribut
| zusammengesetzter Wert; +
Muster: "SZ"-`+Quelle.OID+` +
Beispiel: SZ-123e4567-e89b-12d3-a456-426614174000
| `+Identifikator+`
| `+Name+`
| `+Name+`
| `+Nutzungszustand.Code+` +
hergeleitet über `+Rueckgabebrunnen.rNutzungszustand+`
| `+Nutzungszustand+`
| `+Zweck+`
| `+Zweck+`
| `+Geometrie+`
| `+Geometrie+`
|===

==== Klasse `+Anreicherungsanlage+`
Der Kanton führt keine Daten zu Anreicherungsanlagen. Aus diesem Grund bleibt die Klasse leer.

todo: Erfassungsregeln gemäss Bundesmodell bei der Klassenbeschreibung ergänzen

==== Klasse `+Fassungsstrang_Stollen+`
[cols=2*,options="header"]
|===
| Quellattribut | Zielattribut
| zusammengesetzter Wert; +
Muster: "SZ"-`+Quelle.OID+` +
Beispiel: SZ-123e4567-e89b-12d3-a456-426614174000
| `+Identifikator+`
| `+Fassungstyp.Code+` +
hergeleitet über `+Fassungsstrang_Stollen.rFassungstyp+`
| `+Typ+`
| `+Geometrie+`
| `+Geometrie+`
| berechneter Wert; +
OID aus Grundwasserschutzzone aufgrund geometrischem Verschnitt
| `+Ref_GWSZone+`
| berechneter Wert; +
OID aus Grundwasserschutzbereich aufgrund geometrischem Verschnitt
| `+Ref_GSBereich+`
|===

todo: Erfassungsregeln gemäss Bundesmodell bei der Klassenbeschreibung ergänzen

=== todo Transformation ins WebGIS
* Quellmodell: Das hier beschriebene Datenmodell
* Zielmodell: keines (siehe unten)

==== Allgemeines
Für die WebGIS-Publikation werden die Daten optimiert. Dies ist häufig mit einer Denormalisierung verbunden ("flachwalzen" der Daten). Der Attributumfang richtet sich nach den Anforderungen der zuständigen Stelle und ist im Normalfall geringer als im Ausgangsmodell. Eine weitere Besonderheit kommt den Tabellen der WebGIS-Datenbank zu. Sie weisen Standard-Spalten auf, welche nicht Teil des Datenmodells sind. Es handelt sich um folgende Spalten:

**Standardspalten:**
[cols=2*,options="header"]
|===
| Spaltenname | Beschreibung
m| id | eindeutige Identifikation des Objektes; kann von der OID der Ausgangsdaten abweichen, falls Objekte zum Zweck der Publikation aufgeteilt werden müssen
m| etl_dt | Zeitstempel, an dem der Datensatz in die Tabelle geschrieben wurde (etl: extract - transfer - load)
m| etl_job | Name des Jobs, mit dem die Daten auf die Tabelle geschrieben wurde
m| asof_dt | Datum, an dem am Datensatz die letzten Änderungen vorgenommen wurden. Dieser Wert wird in den Metadaten des Datensatzes nachgeführt.
|===

Das WebGIS bezieht die Daten direkt aus der Datenbank. Aus diesem Grund wird nachfolgend von "Tabelle" und "Spalte" anstelle von "Klasse" und "Attribut" gesprochen. Der Klassenname erscheint lediglich in der Überschrift.

==== Tabelle der `+Waldgrenze+`
[cols=2*,options="header"]
|===
| Quellattribut | Zielspalte
| - - - | (Standardspalten gemäss den Angaben oben)
| `+Typ.Code+` +
hergeleitet über `+Waldgrenze.rTyp+` m| typ
| `+Typ.Name+` +
hergeleitet über `+Waldgrenze.rTyp+` m| bezeichnung
m| Waldgrenze.Geometrie m| geom
|===

==== Tabelle der `+Stockgrenze+`
[cols=2*,options="header"]
|===
| Quellattribut | Zielspalte
| - - - | (Standardspalten gemäss den Angaben oben)
| `+Verfahren.Verfuegungsnummer+` +
hergeleitet über: +
`+Stockgrenze.rWaldgrenze+` &#x2192; +
`+Waldgrenze.Begruendungsverfahren+`
m| verfuegung_datum_nr
m| Stockgrenze.Geometrie m| geom
|===

ifdef::backend-pdf[]
<<<
endif::[]
