== Modelltransformationen
=== Transformation vom Bearbeitungsmodell ins Publikationsmodell
* Quellmodell: https://raw.githubusercontent.com/ch-sz-geo/A064/refs/heads/main/models/SZ_Schutzwald_V1_Bearbeitung.ili[Bearbeitungsmodell "SZ_Schutzwald_V1" (Version: 2025-01-23)]
* Zielmodell: https://raw.githubusercontent.com/ch-sz-geo/A064/refs/heads/main/models/SZ_Schutzwald_V1.ili[Publikationsmodell verwaltungsintern "SZ_Schutzwald_V1_Bearbeitung" (Version: 2025-01-23)]

=== Transformation ins minimale Geodatenmodell des Bundes
* Quellmodell: Das hier beschriebene Datenmodell
* Zielmodell: http://models.geo.admin.ch/BAFU/todo[<Modellname> (Version: 2023-03-20)]

==== Klasse `+Quelle+`
[cols=2*,options="header"]
|===
| Quellattribut | Zielattribut
| zusammengesetzter Wert; +
Muster: "SZ"-`+Quelle.OID+` +
Beispiel: SZ-123e4567-e89b-12d3-a456-426614174000
| `+Identifikator+`
| `+Name+`
| `+Name+`
| `+Grundwasserleitertyp.Code+` +
hergeleitet über `+Quelle.rGrundwasserleitertyp+`
| `+Grundwasserleiter_Typ+`
| `+Quelltyp+`
| `+Quelltyp+`
| `+Fassungsart.Code+` +
hergeleitet über `+Quelle.rFassungsart+`
| `+Fassungsart+`
| `+Nutzungszustand.Code+` +
hergeleitet über `+Quelle.rNutzungszustand+`
| `+Nutzungszustand+`
| `+istTrinkwasser+` +
Regel: "1" = "ja"; "0" = "nein"; leer = "unbekannt"
| `+Trinkwasser+`
| `+Zweck+`
| `+Zweck+`
| `+besteht_oeffentliches_Interesse+`
| `+Oeffentliches_Interesse+`
| `+Schuettung_minimal+`
| `+Schuettung_minimal+`
| `+Schuettung_mittel+`
| `+Schuettung_mittel+`
| `+Schuettung_maximal+`
| `+Schuettung_maximal+`
| `+ist_Zustroembereich_erforderlich+`
| `+Zustroembereich_erforderlich+`
| `+Geometrie+`
| `+Geometrie+`
| `+Wasserversorger+`
| `+Name_WV+`
| berechneter Wert; +
OID aus Grundwasserschutzzone aufgrund geometrischem Verschnitt
| `+Ref_GWSZone+`
| berechneter Wert; +
OID aus Grundwasserschutzbereich aufgrund geometrischem Verschnitt
| `+Ref_GSBereich+`
|===

=== Transformation ins WebGIS
* Quellmodell: Das hier beschriebene Datenmodell
* Zielmodell: keines (siehe unten)

==== Allgemeines
Für die WebGIS-Publikation werden die Daten optimiert. Dies ist häufig mit einer Denormalisierung verbunden ("flachwalzen" der Daten). Der Attributumfang richtet sich nach den Anforderungen der zuständigen Stelle und ist im Normalfall geringer als im Ausgangsmodell. Eine weitere Besonderheit kommt den Tabellen der WebGIS-Datenbank zu. Sie weisen Standard-Spalten auf, welche nicht Teil des Datenmodells sind. Es handelt sich um folgende Spalten:

**Standardspalten:**
[cols=2*,options="header"]
|===
| Spaltenname | Beschreibung
m| id | eindeutige Identifikation des Objektes; kann von der OID der Ausgangsdaten abweichen, falls Objekte zum Zweck der Publikation aufgeteilt werden müssen
m| etl_dt | Zeitstempel, an dem der Datensatz in die Tabelle geschrieben wurde (etl: extract - transfer - load)
m| etl_job | Name des Jobs, mit dem die Daten auf die Tabelle geschrieben wurde
m| asof_dt | Datum, an dem am Datensatz die letzten Änderungen vorgenommen wurden. Dieser Wert wird in den Metadaten des Datensatzes nachgeführt.
|===

Das WebGIS bezieht die Daten direkt aus der Datenbank. Aus diesem Grund wird nachfolgend von "Tabelle" und "Spalte" anstelle von "Klasse" und "Attribut" gesprochen. Der Klassenname erscheint lediglich in der Überschrift.

==== Tabelle der `+Waldgrenze+`
[cols=2*,options="header"]
|===
| Quellattribut | Zielspalte
| - - - | (Standardspalten gemäss den Angaben oben)
| `+Typ.Code+` +
hergeleitet über `+Waldgrenze.rTyp+` m| typ
| `+Typ.Name+` +
hergeleitet über `+Waldgrenze.rTyp+` m| bezeichnung
m| Waldgrenze.Geometrie m| geom
|===

==== Tabelle der `+Stockgrenze+`
[cols=2*,options="header"]
|===
| Quellattribut | Zielspalte
| - - - | (Standardspalten gemäss den Angaben oben)
| `+Verfahren.Verfuegungsnummer+` +
hergeleitet über: +
`+Stockgrenze.rWaldgrenze+` &#x2192; +
`+Waldgrenze.Begruendungsverfahren+`
m| verfuegung_datum_nr
m| Stockgrenze.Geometrie m| geom
|===

[cols="e,m,^,>s",width="25%"]
|===
|1 >s|2 |3 |4
^|5 2.2+^.^|6 .3+<.>m|7
^|8
|9 2+>|10
|===


ifdef::backend-pdf[]
<<<
endif::[]
